### ISSUE TITLE
Executing frontend according to README instructions does not work

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#117]
Starting frontend according to instruction in https://github.com/kbss-cvut/fta-fmea-ui/tree/main#execution produces strange output.

**Comment by blcham** [comment]
@hugomrazek please describe

**Comment by hugomrazek** [comment]
Starting the project according to execution in README results in this
![Screenshot from 2023-08-02 13-27-21](https://github.com/kbss-cvut/fta-fmea-ui/assets/36826106/92604f0e-9b99-4001-b033-1076648392db)

**Comment by hugomrazek** [comment]
Making the project running using Docker works, but it is confusing since there is a section "Execution" in README. README suggest changing .env variable called `GRAPHDB_ZIP` but the variable is actually `GRAPHDB_FILE`. Also the variable needs only name of the file not a path to it, which is not super clear either.

The project is running now but to be completely honest I have no idea ATM how to make contributions - the docker-compose.yml used for deployment pulls the images from github container registry, so I don't know how to set up developer version of the project.
