### ISSUE TITLE
Set up prettier

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#180]
Lately,  since we started to use different IDEs for the development, I experienced a lot of commits that introduced formatting inconsistent with the rest of the code. So, we need to use prettier.

I suggest using the default configuration (i.e., no configuration) of prettier as we use in https://github.com/kbss-cvut/s-forms, https://github.com/kbss-cvut/termit-ui.

A/C:
- we agreed on how to configure a prettier
- prettier is configured in a similar way as in related projects
- the code is reformated according to the prettier configuration

**Comment by blcham** [comment]
@LaChope @ledsoft  @shellyear @Kasmadei

**Comment by blcham** [comment]
I suggest to use default configuration of the prettier

**Comment by ledsoft** [comment]
I suggest to at least set line width to more than 80 characters (I typically use 120)

**Comment by shellyear** [comment]
I suggest this config for the  prettier `module.exports = {
	printWidth: 120,
	tabWidth: 2,
	semi: false,
	trailingComma: "none",
	singleQuote: true,
	endOfLine: "auto",
}` @LaChope @kostobog @ledsoft @Kasmadei @blcham

**Comment by Kasmadei** [comment]
@shellyear sounds good for me. Do we want to add something else ?

**Comment by ledsoft** [comment]
Please, use a semicolon to terminate statements. Even Douglas Crockford [recommends it](https://www.crockford.com/code.html). It prevents hard to spot bugs. And yes, I know that Prettier will put them when such an issue might occur but using them everywhere makes for a more consistent codebase.

 I would also recommend using LF for end of line, so that line endings are the same everywhere (personal experience with LF and CRLF on Linux and Windows machines editing the same code).

I know I am not the owner of this repo, but since @blcham tagged me, these are my opinion.

**Comment by LaChope** [comment]
From its [documentation](https://prettier.io/docs/en/option-philosophy), Prettier is opinionated and encourages to **not** configure it.
> So why are there any options at all?
> 
>     - A few were added during Prettier’s infancy to make it take off at all. 🚀
>     - A couple were added after “great demand.” 🤔
>     - Some were added for compatibility reasons. 👍

So I would recommend use minimal configuration such as `printWidth` but that's it. Also, it will keep consistency within our existing projects.

**Comment by blcham** [comment]
I evaluated the discussion as follows:

The stronger agreement was only on:
```
{ printWidth: 120 }
```

Thus, I added only this rule to the configuration. I am closing the issue -- we can reopen it after some experience with this setting (e.g. in a couple of months).
