### ISSUE TITLE
Strange cutset shown in UI

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#211]
Using internal-auth deployment and "Switch cutsets view" I saw a strange minimal cutset:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/562152a8-389b-4b44-b76d-8370620f752f)

A/C:
- [ ] there is only one cutset shown in UI, when the button "Switch cutsets view" is hit
- [ ] for ordering of cutsets multi-criteria ordering is used as described above (after the ordering the first element is chosen)

**Comment by blcham** [comment]
@LaChope after investigation, reassign the ticket to correct person

**Comment by LaChope** [comment]
I think there are 2 issues:

- From UI:  https://github.com/akaene/fta-fmea-ui/pull/4/files#r1524238736 - Minimal cut sets are not the node with the highest probability but are a group of sets consisting of the smallest combinations of basic events that result in the occurrence of the top event. In this example, as there is a OR gate, there are 4 cut sets. Now, we don't have a way to select which cut set to display, but in the future we will have a side panel with all cutsets that we can select.
- From server: I do not see where the data about cutset is? (see screenshot)

![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/57750426/c41f5743-29a5-49b7-8f6d-0222832d85e6)

**Comment by LaChope** [comment]
It seems like backend works well, all 4 cutsets are returned. The issue seems like there is more than 1 minimal cut set (there are 2), which are shown simultaneously. Instead, we should also stably show one of them.

As of stable ordering, I suggest to use original order within retrieved failure scenarios (i.e. If you have several scenarios with same probabilities within incoming array of scenarios, put them in the same order in "the table").

**Comment by Kasmadei** [comment]
I believe u meant: 
> The number of basic events decreasing
> Concatenation of all alphabetically ordered Labels of basic events in increasing order

**Comment by blcham** [comment]
@Kasmadei I updated the description of multi-criteria ordering as discussed.
