### ISSUE TITLE
Outdated values of FTA tree properties should be clearly marked

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#379]
Motivation:
- we need "stable FTA tree" -- i.e. values computed on FTA tree should not change without explicit request of user. Thus for each node we keep `:probability` property that holds lastly used value.
- on the other hand value of some properties are updated automatically

The properties that are updated automatically without user requests are:
- [x] SNS node / operational value
- [x] SNS node / predicted value
- [x] External reference node / computed value
- [x] minimal operational hours value of whole FTA tree

A/C:
- outdated values are distinguished (clearly marked) in a way that user can see it without interaction with UI (e.g. marking them red)

**Comment by blcham** [comment]
Use state not-synchronized / synchronized

**Comment by kostobog** [comment]
For external node there could be the following out-of-sync states :
- the probability value saved in the external node is different from the calculated value of root node of the referenced fault tree
- out of sync because of updated leaf nodes after fault tree evaluation
- out of sync because of experimental evaluation (i.e. with MOH different  from system MOH)

**Comment by blcham** [comment]
@kostobog There is last missing thing that should be fixed:
![image](https://github.com/user-attachments/assets/9d1c189c-5165-451a-8aae-180e74bb1943)
