### ISSUE TITLE
Implement status of FTA tree

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#428]
This ticket is for both frontend (@Kasmadei) and backend (@kostobog).

I suggest to have 2 statuses:
- synchronized
- not synchronized

@kostobog I want to implement only the easiest way to find out what is not synchronized and solve the rest in the following issues. Thus, I suggest implementing only a not-synchronized state if min. operational hours are set differently than related system.

The FTA tree should have field status.

A/C:
- [x] @kostobog backend returns status
- [x] @kostobog backend returns outdated status when min. operation hours are not synchronized
- [x] @LaChope frontend shows the status in the table of FTA trees
- [x] @LaChope frontend shows status within the FTA tree

**Comment by blcham** [comment]
I vote for option 1) to make title red if it is outdated:
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/f9eb1432-96d4-4ebe-a8b5-fe51dbb6001f)

**Comment by blcham** [comment]
BTW other synonyms to discussed:
- out-of-date
- outdated
- out-of-sync
- not-alligned

**Comment by kostobog** [comment]
@blcham @Kasmadei 
Simple fault tree status is implemented on backend in PR kbss-cvut/fta-fmea#129.
The status is updated on fault tree evaluation with filter. If fault tree has no persisted status the is inferred when fetched. Inferring is supported both for fetching fault tree summaries and fault tree with details.
The status values are
- `ok` - tree specific filter min operational hours has same value as system the system specific one
- `outOfSynch` - otherwise

**Comment by kostobog** [comment]
@blcham @Kasmadei 
See PR #467, it fixes incorrect call to fault tree evaluate.
