### ISSUE TITLE
Fault tree evaluation with min operational hours should not fail due to issues with operational statistics service.

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea-ui#452]
- [x] A **FTA Tool Backend** - resolved in /kbss-cvut/fta-fmea#128
  - catch and log message that fault tree evaluation failed due to operational statistics service
  - do not update the fault tree if the operational statistics service fails or is not properly configured
  - implement check operational statistics service status to allow client to visualize in UI.

- [ ] B **FTA Tool UI** 
   - #454 

- [x] C **Analytics Backend** - resolved in kbss-cvut/ava-analytics#14
  - implement simple status check API for the FTA backend to use to verify the status of the service and the configuration.

**Comment by blcham** [comment]
@kostobog **Based on the time limitations we have**, I believe you are overcomplicating this issue.

I think you should only consider two states right now:
- service is set up
  - just let the server fail, we will see it in developer log
- service is not set up (i.e. URL in environment is "")
  - silently ignore it

**Comment by blcham** [comment]
@kostobog To me, I do not consider it necessary to explain user that operational statistics service is down -- because to me it is rather ERROR, not regular situation that user should be tackled with ... If you feel that it is however needed i do not have problem if u implement it ... 

If you do not think is need it or need it now, please close this ticket.

**Comment by kostobog** [comment]
@blcham
