### ISSUE TITLE
Failure rate is marked as outdated even for newly created FTA node

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/fta-fmea-ui#505]
![image](https://github.com/kbss-cvut/fta-fmea-ui/assets/3962237/ccf65184-b90f-4b99-8a7e-92a85770be02)

**Comment by kostobog** [comment]
@blcham 
If I understand it should show that there is a new value for the predicted failure rate, e.g. someone replaced the old value with a new value (due to re-importing SNS with new prediction). 
However, it also shows if the user changed the selection to `predicted failure rate`. I am not sure if this is a feature or a bug.

The same holds for the operational failure rate. Only in this case the value could change due to operational failure rate being updated from another fault tree, e.g. when someone is experimenting with different `min operational hours` or due to new records being considered in its evaluation.

I don't think there is need to have the orange values when the user changes selection and the form is dirty. 

I can try to make the fields orange only when their value is actually outdated not when user changes selection in the form

**Comment by blcham** [comment]
@kostobog moreover we are missing tooltip why is the number orange.

**Comment by blcham** [comment]
@kostobog  reopening it as i do not see it fixed at KBSS

![image](https://github.com/user-attachments/assets/4c9ed7d7-03ac-4441-ae8f-8f6b1fb1e055)

**Comment by kostobog** [comment]
@blcham 
It works fine for me. Did you try clearing cache?

**Comment by blcham** [comment]
It works aftere clearing cache.
